server:
  port: 8080
  http2:
    enabled: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${AUTH_DB_NAME}
    username: ${AUTH_DB_USER}
    password: ${AUTH_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:changelog/master.yaml
management:
  endpoints:
    web:
      exposure:
        include: "*"

email-service:
  url: http://localhost:8086

oauth2:
  google:
    client-id: client_id
    client-secret: client_secret
    redirect-uri: http://localhost:8080/api/v1/oauth2/google/callback
    auth-url: https://accounts.google.com/o/oauth2/v2/auth
    access-token-url: https://oauth2.googleapis.com/token
    user-info-url: https://openidconnect.googleapis.com/v1/userinfo

    front-end-base-url: http://localhost:5173

